### PR TITLE
add a list of transmitter devices

### PR DESCRIPTION
**Pull request by janusw**
This PR makes a start with setting up a list of transmitter devices, as proposed in #52.

The INVOLI device is included, but it's not clear which transport types it supports (the website only mentions "Wi-Fi", but does not say whether NAN or Beacon is meant). The other entries I have verified myself.

### CODE REVIEW

**Comment by janusw** [comment]
> The INVOLI device is included, but it's not clear which transport types is supports (the website only mentions "Wi-Fi", but does not say whether NAN or Beacon is meant).

Looking a bit closer, the video at https://www.youtube.com/watch?v=7bsdSZIcb44 reveals an ODID screenshot (at 0:41) that shows `NAN ID: 100` as MAC, which indicates that the device supports WiFi NAN at least (possibly Beacon in addition?). There is no mention of Bluetooth whatsoever. 7964f11d3c38d81e45a42c8905e7bf6069cad77c fills the details in the table accordingly.

**Comment by lukasbrchl** [comment]
Hi Janus, did you test the Mavic 3 yourself? Because we did with the latest FW and there was no Remote ID option/settings. So I assume, that people who tested this functionality had some "unlisted" fw.

**Comment by janusw** [comment]
> Hi Janus, did you test the Mavic 3 yourself?

No, I did not. As the commit mentions, it is purely based on the information provided in the links.

> Because we did with the latest FW and there was no Remote ID option/settings. So I assume, that people who tested this functionality had some "unlisted" fw.

Oh, that's interesting. Thanks for the comment. If you cannot confirm it, then this commit should be discarded.

**Comment by janusw** [comment]
> > Because we did with the latest FW and there was no Remote ID option/settings. So I assume, that people who tested this functionality had some "unlisted" fw.
> 
> Oh, that's interesting. Thanks for the comment. If you cannot confirm it, then this commit should be discarded.

I removed the commit from this PR for now.

**Comment by friissoren** [comment]
I will take a deeper look at this later on. I think some disclaimer text at least would be needed. I can add that later.

Just a few questions now. Should the FW version for the drone/add-on that has been tested be added?

When you tested the Anafi drone, did you fly it? Both the US and EU standards/rules only require you to broadcast after take-off.

I tested a borrowed Mavic 2 Pro a couple of weeks ago (of course forgot to write down the firmware version) and it did not broadcast anything even when in the air. Receiver was a Samsung Galaxy S10 so it should have picked up any type of signal.

It would probably also be good to have some information about the receiver device that was used for testing. We already know that many phones don't support receiving all broadcast types (and there are [weird things](https://github.com/sxjack/uav_electronic_ids/issues/9) going on with some transmitter/receiver combinations for Wi-Fi Beacon).

**Comment by janusw** [comment]
> I will take a deeper look at this later on. I think some disclaimer text at least would be needed. I can add that later.

That would be great. Thanks.

> Just a few questions now. Should the FW version for the drone/add-on that has been tested be added?

Yes, in particular for the drones this can be useful / relevant. For the Anafi, the DRI support was added with a particular FW version. I can look it up.


> When you tested the Anafi drone, did you fly it? Both the US and EU standards/rules only require you to broadcast after take-off.

Yes, I tried it both in flight and on the ground, and it transmitted in both cases. IIRC it even started broadcasting messages when the GPS position was not known yet. But I need to re-try in order to be sure.


> I tested a borrowed Mavic 2 Pro a couple of weeks ago (of course forgot to write down the firmware version) and it did not broadcast anything even when in the air. Receiver was a Samsung Galaxy S10 so it should have picked up any type of signal.

Did you see any Remote-ID section in the settings? If not, it probably does not do anything.

I know that DJI was active regarding DRI in the past and that they had some beta-FW with DRI support, but it seems they're taking their time to push it into consumer products. Also I was surprised that this Youtube video claimed that the Mavic 3 is broadcasting WiFi Beacon messages, because I thought DJI would be using WiFi NAN.


> It would probably also be good to have some information about the receiver device that was used for testing. We already know that many phones don't support receiving all broadcast types

In principle you're right, but IMHO it would be overkill to include the receiver information in the table. The number of possible combinations is huge. I think it should be enough to just list all broadcast types that have been confirmed, and leave those open that are unconfirmed. If someone is reporting new data, they should ideally provide information about the receiver device, but to my mind this is not essential.

Btw, my tests were mostly done with a Samsung Galaxy S21+ (which has complete coverage of all BLE & WiFi types), but also with other Android devices (and for BLE I also tested with an iPhone, but of course not with the ODID app in this case).

**Comment by friissoren** [comment]
> > I tested a borrowed Mavic 2 Pro a couple of weeks ago (of course forgot to write down the firmware version) and it did not broadcast anything even when in the air. Receiver was a Samsung Galaxy S10 so it should have picked up any type of signal.
> 
> Did you see any Remote-ID section in the settings? If not, it probably does not do anything.

There were menu items related to remote ID and it was turned on. However, it could be that this is the remote ID signals that are related to DJI Aeroscope? It would be strange if you were able to turn of the transmission of those though. It is a bit of a mystery.

> I know that DJI was active regarding DRI in the past and that they had some beta-FW with DRI support, but it seems they're taking their time to push it into consumer products. Also I was surprised that this Youtube video claimed that the Mavic 3 is broadcasting WiFi Beacon messages, because I thought DJI would be using WiFi NAN.

The US rules will most likely [converge](https://github.com/opendroneid/opendroneid-core-c#comparison) on allowing only Wi-Fi beacon (or BT). Not NAN. See note 7. For any company selling drones globally, it would therefore be easier to use only Wi-Fi Beacon and ditch NaN completely. I cannot say anything specific about what each company will choose to do though.

I am not sure what video you are referring to but at least [this one](https://forum.dji.com/thread-254110-1-1.html) shows Wi-Fi beacon transmit for the Mavic 3. No indication about the drone Firmware version though.

> Btw, my tests were mostly done with a Samsung Galaxy S21+ (which has complete coverage of all BLE & WiFi types), but also with other Android devices (and for BLE I also tested with an iPhone, but of course not with the ODID app in this case).

So you have a BT4 iOS receiver implementation?

**Comment by janusw** [comment]
> I am not sure what video you are referring to but at least [this one](https://forum.dji.com/thread-254110-1-1.html) shows Wi-Fi beacon transmit for the Mavic 3. No indication about the drone Firmware version though.

Yes, that's the one I was referring to.


> > Did you see any Remote-ID section in the settings? If not, it probably does not do anything.
> 
> There were menu items related to remote ID and it was turned on. However, it could be that this is the remote ID signals that are related to DJI Aeroscope? It would be strange if you were able to turn of the transmission of those though. It is a bit of a mystery.

The video above shows a settings screen with both an Aeroscope and a Remote-ID section (in Italian, though). For Aeroscope you can modify some settings AFAIK, but not turn it off completely.


> > I know that DJI was active regarding DRI in the past and that they had some beta-FW with DRI support, but it seems they're taking their time to push it into consumer products. Also I was surprised that this Youtube video claimed that the Mavic 3 is broadcasting WiFi Beacon messages, because I thought DJI would be using WiFi NAN.
> 
> The US rules will most likely [converge](https://github.com/opendroneid/opendroneid-core-c#comparison) on allowing only Wi-Fi beacon (or BT). Not NAN. See note 7. For any company selling drones globally, it would therefore be easier to use only Wi-Fi Beacon and ditch NaN completely. I cannot say anything specific about what each company will choose to do though.

Very interesting. In the first ASTM version it was the other way around, right? Only NAN was mandatory, and Beacon was not covered at all. Interesting that this was turned around. This would definitely explain why DJI would change its mind.

> > Btw, my tests were mostly done with a Samsung Galaxy S21+ (which has complete coverage of all BLE & WiFi types), but also with other Android devices (and for BLE I also tested with an iPhone, but of course not with the ODID app in this case).
> 
> So you have a BT4 iOS receiver implementation?

Yes, but it's not open source (and not publicly available yet).

**Comment by janusw** [comment]
> > Just a few questions now. Should the FW version for the drone/add-on that has been tested be added?
> 
> Yes, in particular for the drones this can be useful / relevant. For the Anafi, the DRI support was added with a particular FW version. I can look it up.

Added the FW info in 32d975f5208340726382ce2e756a669b4eacaeab.

**Pull request merged**
