### PR TITLE
Update list

### PR DESCRIPTION
**Pull request by friissoren**
I did some clean-up of the list to make it easier to edit and I cross-checked it against the old Excel sheet and fix some entries here and there.

### CODE REVIEW

**Comment by janusw** [comment]
One comment here: Wouldn't it be useful to sort the list in some way? Currently I see no particular order, except for the fact that Samsung comes first and brands seem to be aggregated in blocks :)

Possible ordering schemes that come to mind:
* alphabetical by brand/model
* degree of support
* chipset
* ...

Also, wouldn't it be a good idea to add the OS version, since that might be relevant for some of the results?

**Comment by lukasbrchl** [comment]
@friissoren, thanks for the suggested improvements. I agree with removing the question marks and also thanks for fixing up the testing dates. 

I would like to just quickly discuss one thing. Do you think it is appropriate to add a note to each device where we don't know about the LR support? Because some people might go through the elimination test, but they don't have a second device to confirm the LR support

Btw, One Plus Nord 5G and One Plus Nord 5G should have 1/2021 in the elimination column. But I can edit this in further PR if needed.

1. I would recommend removing the comment from Galaxy Tab S6.

**Comment by lukasbrchl** [comment]
@janusw, I moved this discussion about ordering to #15 as this might be a little more complex.

Concerning the OS version, I discarded this idea. Here are its cons:
- You would need an OS column for each technology -  BT5 LR, Wi-Fi Beacon, Wi-Fi NAN
- It is not only about the Android version but some vendor-specific implementations might also play a role (not sure how to capture those).

My suggestion is to keep for each of the tests the date and assume that it was tested with the newest OS available. This simplifies things a little bit and is subject to errors, but in my opinion, it still works better than capturing the OS in a separate column.

**Comment by friissoren** [comment]
I removed the "Does this receive LR or not?" comments. 

For the Huawei P30 and P30 Pro, it is not clarified whether they receive continuously or not. Do you have either or both of those  devices?

**Comment by lukasbrchl** [comment]
Unfortunately, I don't have the Huawei devices available right now. But we plan to do some thorough testing when the stores open so we can retest those and then clarify the functionality in the comment column.

**Comment by janusw** [comment]
> @janusw, I moved this discussion about ordering to #15 as this might be a little more complex.

Sure, thanks :)

> Concerning the OS version, I discarded this idea. Here are its cons:
> 
>     * You would need an OS column for each technology -  BT5 LR, Wi-Fi Beacon, Wi-Fi NAN

I was rather thinking of one new column that would specify for each line (=device), with which OS the test was done.

So if you have one device that was tested with two different OS versions, that would be two lines.

>     * It is not only about the Android version but some vendor-specific implementations might also play a role (not sure how to capture those).

Of course the OS version is not the *only* thing that is playing a role. But the combination of hardware and OS version should at least guarantee a unique test result (while specifying the hardware alone might not be enough) ...

**Pull request merged**
