### PR TITLE
Supported Smartphones: update Zenfone 6 & add missing links

### PR DESCRIPTION
**Pull request by janusw**
This updates the Zenfone6 info in the table of supported smartphones:
* BT5 reception was tested with a DroneTag Mini (proofs included)
* WiFi Beacon reception was tested with a Parrot Anafi (proof included)

Moreover, a couple of missing links are added to the table (to proofs which are already present: they were added in 6d0dd4413bc072845c75f8c411018ee0f5c4380d, but without the links).

### CODE REVIEW

**Comment by janusw** [comment]
One thing I should note here: Despite the fact that the `bt_lr_rssi` screenshot indicates continuous reception, I'm not fully convinced that this is actually the case. In fact I have been seeing larger gaps with DRI receiver applications.

The point is: I have configured the DroneTag device to send DRI via BT5 only. Still, nRF Connect shows not only extended advertisements, but also legacy ones. The latter are apparently not DRI messages, but probably related to the fact that the device can be configured with an app via a Bluetooth connection and therefore advertises itself via legacy advertisements.

I found no way in nRF Connect to filter on the BT5 DRI advertisements only, therefore the RSSI graph presumably shows a mixture of both the BT5 DRI advertisements and BT4 non-DRI advertisements. This seems to be a minor flaw in the methodology. Any ideas on how to improve that?

**Comment by lukasbrchl** [comment]
Hello Janus, thanks for pointing this out. You are correct, the Mini also advertises connectable BT4 messages which allow phones to connect and configure the device. This cannot be at the moment stopped. However, I don't see any flaw in the methodology as it speaks about using a second mobile device and nRF Connect App to setup the test.

**Comment by janusw** [comment]
> Hello Janus, thanks for pointing this out. You are correct, the Mini also advertises connectable BT4 messages which allow phones to connect and configure the device. This cannot be at the moment stopped.

Hi Lukas, thanks for confirming my assumptions :)

This behavior per se is not a problem, of course.

> However, I don't see any flaw in the methodology as it speaks about using a second mobile device and nRF Connect App to setup the test.

Well, the methodology says:

> Use another device (Master) that passed the Elimination Criteria [...]
> Alternatively: use any other device that supports Long Range advertisements

So what I'm doing seems to be 'allowed'.

To get around this minor problem: Maybe there is some way to make nRF Connect filter on BT5 only (or on DRI content), but I did not find any so far ...

**Comment by lukasbrchl** [comment]
Ok, got your point Maybe we should put some small note that user should be aware that some add-on devices might also advertise BT4 connectable messages so it cannot be tested then. What do you think @friissoren?

**Comment by friissoren** [comment]
Sounds reasonable to me. Go ahead, if you have a good way of wording that.

**Pull request merged**
