### PR TITLE
Update French translations

### PR DESCRIPTION
**Pull request by NasH5169**
Hi team,

Could you please take a look at the updated French translations fixes?

Thanks!

### CODE REVIEW

**Comment by friissoren** [comment]
Thanks. This is better than what is currently included (see issue #72).

However, I wonder if it would still be possible to improve the layout on the Info screen a bit.
Screenshot_20221107-152048_OpenDroneID

The longitude for both the location and the operator are getting cut off. Is it possible to shorten "Précision de l’heure" somehow and still keep the meaning of that field? 

And in the operator box, some of the longer text strings there?

At the top, "Vu pour la dernière fois" seems quite long also and causes the MAC address to be partly hidden.

Screenshot_20221107-152121_OpenDroneID

On the main view, is it possible to have just "INFO" instead of "INFORMATION"?

The "Identité de base 1" etc. are being bent also but I think I can fix that in the layout definition file. They are currently defined unnecessarily short. There is room on the screen for those strings.

**Comment by NasH5169** [comment]
Hi Søren,

I will adjust the labels (INFO etc) but I will also check if we can fix the main blue labels of each section.

Another commit will come.

**Comment by NasH5169** [comment]
Add a new commit to adjust the translations and also the layout, feel free to test again.

**Comment by friissoren** [comment]
Thank you. This looks very nice. I appreciate your help with this.

**Pull request merged**
