### PR TITLE
Add Japanese to multi-language

### PR DESCRIPTION
**Pull request by muramura**
The remote ID for Japan is the F3411-19 specification.
This tool is useful in Japan.
I would like to support Japanese language.
I believe that supporting Japanese language will make it easier for many Japanese people to use this tool.

Japanese display

IMG-8798

IMG-8799

IMG-8800

### CODE REVIEW

**Comment by friissoren** [comment]
Very interesting.
I am traveling right now and won't be able to review. Please wait a few days and I will take a look.

**Comment by gabrielcox** [comment]
Thank you @muramura , This is a great contribution!  I look forward to seeing it integrated.  Not only does it add Japanese support, but easy enablement of other languages.

**Comment by gabrielcox** [comment]
Requested translation review by @juntakei .

**Comment by juntakei** [comment]
This is great. I had some chat with Gabriel. Let me suggest some changes. 

- “Location” ->  "位置/方向/速度"
- “Direction” ->  "方向"
- “Operation” -> "運用情報"
- “System/Operator” -> “システム /オペレーター”
- "Area Ceiling" -> "エリア上限"
- "Area Floor" -> "エリア加減"


Other than that it looks good for me. @gabrielcox , @muramura

**Comment by muramura** [comment]
I have revised the following items.
I modified the following items, but  “システム /オペレーター” is too long, so I changed it to “システム /操縦者”.
Also, I think "エリア加減" should be "エリア下限".

“Location” -> "位置/方向/速度"
“Direction” -> "方向"
“Operation” -> "運用情報"
“System/Operator” -> “システム /オペレーター”
"Area Ceiling" -> "エリア上限"
"Area Floor" -> "エリア加減"

Screenshot from 2022-05-26 22-31-54

**Comment by juntakei** [comment]
@muramura  @gabrielcox Looks good for me. Thank you for the update.

**Comment by friissoren** [comment]
Thanks a lot. This is a very good addition.

**Pull request merged**
